### ISSUE TITLE
Installations Anleitung und Script

### ISSUE THREAD

**Issue by martingrimmer** [LID-DS/LID-DS#12]
## Installations Anleitung bereitstellen
* Anleitung ins Wiki
* zusätzlich noch ein Installationsscript schreiben

**Comment by boneymoy88** [comment]
https://github.com/LID-DS/LID-DS/wiki/Run-couchdb_example

**Comment by martingrimmer** [comment]
Das 2012er Szenario auch zum Laufen bringen damit bitte. ;)
