### ISSUE TITLE
Analyse LID-DS-2021

### ISSUE THREAD

**Issue by martingrimmer** [LID-DS/LID-DS#163]
**Alle Werte pro Szenario (Training, Validation, Test)**
Ausgabeformat: json

| **Syscalls** | **Abgeschlossen (nein:🟥, ja: 🟩)** |
|---------|--------|
| Verteilung der System Calls                  | 🟥 |
| Anzahl der System Calls                        | 🟥 |
| ø Anzahl der System Calls                     | 🟥 |
| ø Anzahl der Threads und Prozesse      | 🟥 |
| ø Anzahl der User                                  | 🟥 |
| **Packets**                                             | **Abgeschlossen (nein:🟥, ja: 🟩)** |
| Verteilung der Protokolle                       | 🟥 |
| ø Anzahl der Pakete                               | 🟥 |
| ø Anzahl der verwendeten IP Adressen | 🟥|
| Verteilung der HTTP Methoden             | 🟥 |
| **Resources**                                         | **Abgeschlossen (nein:🟥, ja: 🟩)** |
| Min, Max, Avg aller Werte in den rc Files | 🟥 |
| **Metadata**                                         | **Abgeschlossen (nein:🟥, ja: 🟩)** |
| Aufnahmezeit Min, Max, Avg und Summe |🟥|
| Anzahl der Verwendeten Verhalten(Container) |🟥|
| **HIDS**                                                 | **Abgeschlossen (nein:🟥, ja: 🟩)** |
| Baseline mit STIDE: mit und ohne Threads |🟥|

**Comment by alkor200** [comment]
@martingrimmer @boneymoy88 

für Paketstatistiken siehe #172

**Comment by martingrimmer** [comment]
siehe #250
