### ISSUE TITLE
Hello, The link to the IDS-DS dataset is not effective, is the link outdate?

### ISSUE THREAD

**Issue by ShuangbiaoDai** [LID-DS/LID-DS#290]

**Comment by martingrimmer** [comment]
Hello, which link exactly do you mean?

**Comment by martingrimmer** [comment]
I re-uploaded the LID-DS-2019 and updated the link to it in the readme.md.
see: https://github.com/LID-DS/LID-DS/blob/master/README.md

**Comment by ShuangbiaoDai** [comment]
yeah, now the link is effective, thanks for your reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Martin ***@***.***&gt;; 
发送时间: 2022年3月7日(星期一) 晚上6:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LID-DS/LID-DS] Hello, The link to the IDS-DS dataset is not effective, is the link outdate? (Issue #290)





 
I re-uploaded the LID-DS-2019 and updated the link to it in the readme.md.
 see: https://github.com/LID-DS/LID-DS/blob/master/README.md
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
