### ISSUE TITLE
neues BB: FileDescriptor

### ISSUE THREAD

**Issue by martingrimmer** [LID-DS/LID-DS#342]
Ein BuildingBlock, welcher den Filedescriptor eines Systemcalls extrahiert.
 Beispielnutzung: 
```python
bb_fd = FileDescriptor(mode=FileDescriptor.String) # extrahiert des fd als String
bb_fd = FileDescriptor(mode=FileDescriptor.ID) # extrahiert des fd als Integer
```

Rückgabewerte:
- wenn kein FileDescriptor im SysctemCall vorhanden ist: none
- wenn ein FileDescriptor vorhanden ist: (fd) Tuple mit einem Element
- wenn zwei FileDescriptoren vorhanden sind: (fd1,fd2) Tuple mit zwei Elementen in der entsprechenden Reihenfolge (z.B. wie bei sendfile)

Beispiel syscall mit einem fd:
```
1159 00:27:12.310259734 6 33 apache2 15862 > writev fd=12(<4t>172.17.0.21:46790->172.17.0.19:443) size=31 
```

**Comment by alkor200** [comment]
@martingrimmer das hier ist schon reviewed und im Master
