### ISSUE TITLE
[LID-DS 21] Sanity Checks vor Aufzeichnung

### ISSUE THREAD

**Issue by alkor200** [LID-DS/LID-DS#53]
um sicherzustellen, dass das Normalverhalten auf dem victim korrekt ausgeführt wurde wäre es gut eine Möglichkeit zu haben dies zu überprüfen.

Ideen:
- Analysieren der scap files ob erwartetes Verhalten eingetreten ist
  - Mittels Sysdig Inspect das erwartete Verhalten überprüfen
  - Wie sieht das Victim aus, wenn keine Normalverhalten und kein Angriff ausgeführt wird.
- Analyse der durch Docker Stats erzeugten .res files. Hier vor allem network receive zu dem Zeitpunkt an dem Normalverhalten starten sollte

**Comment by alkor200** [comment]
Notizen:
- couchdb mit Fullchain wird sehr groß - 500MB bei 50 Sekunden

**Comment by alkor200** [comment]
https://docs.google.com/document/d/1tFpuUUOE3HeoZymbkxaqVRQg9nQC3tB-R7iUlSndxIw/edit?usp=sharing

**Comment by boneymoy88** [comment]
Set warmup_time to 3 sec and use first parameter as to specify if running normal behavior.

example: 
    warmup_time = 3
    run_normal_behavior = bool(int(sys.argv[1]))
    if run_normal_behavior:
        min_user_count = 10
        max_user_count = 25
        user_count = random.randint(min_user_count, max_user_count)
    else:
        user_count = 0

**Comment by boneymoy88** [comment]
To choose sampling strategy look at https://lidds.slack.com/files/UT51D8JCU/F01TWGTQVRB/toni_rucks_thesis_final.pdf
page 31ff.
